
import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import MainHeader from "@/shared/header/Header";
import { Space_Grotesk } from "next/font/google";
const grotesque = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // adjust as needed
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body  className={`${grotesque.className} antialiased`}
       data-new-gr-c-s-check-loaded="14.1246.0"
      data-gr-ext-installed=""
      cz-shortcut-listen="true"
      >
        <ReduxProvider>
          <MainHeader />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
